### ISSUE TITLE
[ FF7 ] Various bugs

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#156] opened 2021-02-02 20:48 UTC
The music resume feature on known areas of the game makes it so that after the first visit the game "remembers" where the music was at, and the next visit the music continues form where it left. This is the expected behaviour for many areas in the game. There are however some exceptions. For example after winning at the Battle Arena the music continues from where it left (if one loses instead the Arena music starts again). The Arena music should always start from the beginning whether one wins or loses, that's the correct behaviour. The same happens at the Chocobo Races, the music of the next race continues from where it left, where it should begin again from the start.

In the snowboard minigame Time Attack mode, the music follows your actions, the tempo becoming faster if one does good, and slower if one does bad. The pitch of the music should lower when you slow down, and this happens correctly, but when one goes full speed the music pitch becomes too high. In Youtube videos of the PSX version one can hear that the expected behaviour for when one goes fast in the Time Trials is that the music's tempo becomes faster, but the pitch doesn't actually change, remaining the normal one for that music track.

The submarine minigame doesn't start. Trying to play it hangs the game. Trying to exit makes the game crash.

The Fort Condor minigame UI transparency is broken, meaning that some elements, like the hand pointer and others, appear transparent when they should be solid. (Vanilla textures)

FFNx-v1.8.1.152

GTX 970 latest drivers installed

Vanilla FF7 except for FF7 SYW v5 remastered pre-rendered backgrounds (except the minigames) and Anxious Heart 06 for the music.

**Comment by julianxhokaxhiu** [comment] 2021-02-02 21:31
FIrst of all thank you very much for the bug reporting, although the idea of an issue is that is a single one, not a collection of them, because of this, the current issue would be difficult to track. Therefore we will use this just to discuss about them, but I'd invite you in creating single issues as single use cases in order to tackle them one by one.

> The music resume feature on known areas of the game makes it so that after the first visit the game "remembers" where the music was at, and the next visit the music continues form where it left. This is the expected behaviour for many areas in the game. There are however some exceptions. For example after winning at the Battle Arena the music continues from where it left (if one loses instead the Arena music starts again). The Arena music should always start from the beginning whether one wins or loses, that's the correct behaviour. The same happens at the Chocobo Races, the music of the next race continues from where it left, where it should begin again from the start.

I suppose this is an area of expertise of @myst6re therefore I'd appreciate his feedback on this point.

> In the snowboard minigame Time Attack mode, the music follows your actions, the tempo becoming faster if one does good, and slower if one does bad. The pitch of the music should lower when you slow down, and this happens correctly, but when one goes full speed the music pitch becomes too high. In Youtube videos of the PSX version one can hear that the expected behaviour for when one goes fast in the Time Trials is that the music's tempo becomes faster, but the pitch doesn't actually change, remaining the normal one for that music track.

Me and @myst6re are already aware of this and that's purely an implementation workaround. Another solution proposed by Satsuki was to not add this effect at all, but I was against as it should anyway a different behavior even if it sounds "wrong". The correct implementation requires again another library on top, adding more complexity to the current code for a minigame. Therefore I'd personally pass on this and keep it the way it is. If someone is not satisfied, can turn off the external music behavior and keep the original one.

> The submarine minigame doesn't start. Trying to play it hangs the game. Trying to exit makes the game crash.

I'd need to test it it's the very first time I'm hearing about this. Thanks for the report.

> The Fort Condor minigame UI transparency is broken, meaning that some elements, like the hand pointer and others, appear transparent when they should be solid. (Vanilla textures)

A screenshot of this issue would be more helpful than thousands of words. Thank you in advance.

**Comment by daedrixxx2** [comment] 2021-02-02 21:37
Thanks for your answers, and sorry for the wrong entry in the bug checking section. Should I re-open the issues? At least for n° 1, 3, and 4, each one of them separately?

**Comment by julianxhokaxhiu** [comment] 2021-02-02 21:50
> Thanks for your answers, and sorry for the wrong entry in the bug checking section. Should I re-open the issues? At least for n° 1, 3, and 4, each one of them separately?

Not yet, let's wait for Myst to hop onboard so we can clarify first the next steps. Meanwhile I'll test the submarine one :)

> Obviously the external music behavior can't be turned off just for the snowboard minigame section. If I turn it off I'll lose all the bug fixes, right? If so, I'll just live with the minigame bug.

I'm not sure about which bugfixes are you talking about but I think most of the fixes we have do work on both modes as we did them at the engine level. Where a piece of code was hooked entirely, we added manual support for both modes. So you should have them using the original layer too. Anyway, you could turn it off for the snowboard minigame and then turn it on for the rest of the game. I mean, it's up to you :)

**Comment by daedrixxx2** [comment] 2021-02-02 23:09
> The Fort Condor minigame UI transparency is broken, meaning that some elements, like the hand pointer and others, appear transparent when they should be solid. (Vanilla textures)

> A screenshot of this issue would be more helpful than thousands of words. Thank you in advance.

![Immagine](https://user-images.githubusercontent.com/61243321/106673994-d52cd000-65b2-11eb-86c1-4b758c917a3d.png)
![Immagine1](https://user-images.githubusercontent.com/61243321/106673997-d6f69380-65b2-11eb-9ae1-962db49c448f.png)
![Immagine2](https://user-images.githubusercontent.com/61243321/106674001-d78f2a00-65b2-11eb-9518-1aa933c8291a.png)
![Immagine3](https://user-images.githubusercontent.com/61243321/106674006-d958ed80-65b2-11eb-9840-5eb8be22ebdc.png)

Here are the screenshots of the Fort Condor UI transparency problems. The errors are circled in red. In the last image the element circled in green is behaving correctly.

> If someone is not satisfied, can turn off the external music behavior and keep the original one.

I've searched in the settings, and deactivated any settings connected with music, but it didn't seem to make any difference. Which setting controls the external music behavior?

#[USE EXTERNAL MUSIC]
# This flag will enable/disable the support of an enhanced audio layer to reproduce music in-game.
# If you leave out the default configuration FFNx will autodetect your environment and will set it to the best available option.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
use_external_music = false

#[EXTERNAL MUSIC RESUME]
# This flag will enable the support for music resume on known areas of the game ( for eg. World-Map ).
# If you enable this flag, instead of starting the OST for a known area from the beginning everytime, it will resume where you left it off the last time you visited it.
external_music_resume = true

#[EXTERNAL MUSIC PATH]
# Path of the external music files
# Will try to load from this path before using the default for your Version of the game
# Defaults:
# - FF7 1998: music/vgmstream ( 7h-era compatibility )
# - FF7 eStore: data/music_ogg
# - FF7 Steam: data/music_ogg
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
external_music_path = ""

#[EXTERNAL MUSIC EXTENSION]
# The type of file to search for. By default is ogg.
# You can use a list to specify multiple extensions, ordered by priority.
# Example: ["minipsf", "ogg"]
# Supported extensions:
# - https://github.com/losnoco/vgmstream#supported-file-types
# - psf, psf2, minipsf, minipsf2 (PSF and PSF2) if you provide the Highly Experimental BIOS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
external_music_ext = "ogg"

#[EXTERNAL MUSIC HIGHLY EXPERIMENTAL BIOS]
# This flag will enable support to PSF and PSF2 formats.
# You need to provide a BIOS generated for the Highly Experimental project (hebios.bin).
# To find one compiled BIOS: https://git.lopez-snowhill.net/chris/foo_psf
# To generate one: https://git.lopez-snowhill.net/chris/highly_experimental
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
he_bios_path = ""

**Comment by julianxhokaxhiu** [comment] 2021-02-02 23:34
Thanks for the screenshots, I'll check that too. I'm on the Submarine one, I found out why it's crashing but it's a recent issue caused by the frame limiting.

> I've searched in the settings, and deactivated any settings connected with music, but it didn't seem to make any difference. Which setting controls the external music behavior?

`use_external_music` is the one, if that's false already, then you're using the original MIDI. If that's wrong, then it means the game was shipped with a wrong behavior :D

**Comment by daedrixxx2** [comment] 2021-02-02 23:49
> use_external_music is the one, if that's false already, then you're using the original MIDI. If that's wrong, then it means the game was shipped with a wrong behavior :D

As you can see it's set to false. I have Anxious Heart installed, so maybe it has replaced the MIDI and FFNx detects it as the only option. So it uses that, while leaving the external music on as it's the only available option.

**Comment by julianxhokaxhiu** [comment] 2021-02-03 00:27
> > use_external_music is the one, if that's false already, then you're using the original MIDI. If that's wrong, then it means the game was shipped with a wrong behavior :D
> 
> As you can see it's set to false. I have Anxious Heart installed, so maybe it has replaced the MIDI and FFNx detects it as the only option. So it uses that, while leaving the external music on as it's the only available option.

No idea, I'd need to try the mod. Btw I've fixed the submarine minigame now. Look forward for the next canary :)

**Comment by julianxhokaxhiu** [comment] 2021-02-03 00:34
Related to the Fort Condor minigame, I am not able to replicate your texture bug, so it looks like you're using a mod which triggers that behavior. Please make sure you use the vanilla `FFNx.toml` before testing. If a behavior is triggered because of a flag, please let me know which ones did you change. Thank you!

**Comment by daedrixxx2** [comment] 2021-02-03 01:07
I found out what's causing the Fort Condor bug. I'm using Satsuki's FF7 SYW v5 remastered pre-rendered backgrounds (only the backgrounds for this specific minigame, meaning from map0_00.dds to map7_00.dds), but I've always used them no issues. As soon as I remove the HD backrounds from the condor folder the bug disappears.

**Comment by julianxhokaxhiu** [comment] 2021-02-03 13:33
> I found out what's causing the Fort Condor bug. I'm using Satsuki's FF7 SYW v5 remastered pre-rendered backgrounds (only the backgrounds for this specific minigame, meaning from map0_00.dds to map7_00.dds), but I've always used them no issues. As soon as I remove the HD backgrounds from the condor folder the bug disappears.
> In the later versions of FFNx something must have caused this bug when using custom backgrounds with the vanilla UI.

I'm personally using the SYW5 pack and I'm not able to replicate the issue. Perhaps consider using the full pack instead of just some files.

**Comment by daedrixxx2** [comment] 2021-02-03 14:52
I'do just that, but the english "remastered UI" looks horrible...
![eunit01_00](https://user-images.githubusercontent.com/61243321/106763732-6e052f00-6637-11eb-93b4-51e4349d1f4d.PNG)

While you french got a proper remastered UI
![funit01_00](https://user-images.githubusercontent.com/61243321/106763928-9c830a00-6637-11eb-9189-7fcda77517d4.png)

I hope Satsuki does a proper english version...

**Comment by julianxhokaxhiu** [comment] 2021-02-03 15:12
He's working on something that will be released soon. Can't say more as its on his end to announce that :)

**Closed** 2021-02-06 14:47 UTC
Labels: bug, question
