### ISSUE TITLE
[ Common ] FFNx Logo Blackscreen

### ISSUE THREAD

**Issue by ChthonVII** [julianxhokaxhiu/FFNx#573] opened 2023-05-29 14:35 UTC
It looks like commit 3437968 is buggy. I'm getting a blackscreen for the duration of the FFNx logo.

I stuck in some trace calls, and find that: (1) DrawFFNxLogoFrame() _is_ getting called for every frame 0 through 180. (So why isn't it showing anything?) And, (2) drawFFNxLogoFrame() is also getting called ~100 times for frame 180. (That's probably not right.) I didn't have any luck debugging because it looks like it should be working.

Reverting this commit brought the logo back.

**Comment by julianxhokaxhiu** [comment] 2023-05-29 21:12
The only occasion I found out this happens is when DevTools is enabled. Is that happening to you as well? Did you enable the DevTools in the `FFNx.toml`?

**Comment by ChthonVII** [comment] 2023-05-30 01:32
Nope, dev tools not enabled. It just failed straight out of the box.

Settings were 4K fullscreen, 6x internal resolution, lighting on, widescreen off, 60fps on.

**Comment by julianxhokaxhiu** [comment] 2023-05-30 13:20
Thanks, I'll try to test this later here and I'll let you know how it goes with those settings. Can I please ask you to upload also your `FFNx.toml` used?

**Comment by ChthonVII** [comment] 2023-05-31 07:20
Afraid that toml file has been overwritten a few times since then. I'd have to recompile the broken version to reproduce.

**Comment by ChthonVII** [comment] 2023-07-11 03:54
This issue persists with the new canary.

**Comment by ChthonVII** [comment] 2023-07-12 12:18
Oh right, now that I've got a binary with this bug again, I can provide FFNx.toml for it. Here's one.

[FFNx.toml.zip](https://github.com/julianxhokaxhiu/FFNx/files/12027769/FFNx.toml.zip)

The bug also manifests with widescreen turned on, ceteris paribus.

**Comment by dotaxis** [comment] 2023-10-08 08:29
This seems to be directly affected by the `enable_lighting` toggle.

FFNx logo appears when advanced lighting is disabled.

**Comment by julianxhokaxhiu** [comment] 2023-10-08 10:52
Root cause was not related to Widescreen but as @dotaxis pointed out was related to Lighting. Pushed a fix. Thanks all!

**Closed** 2023-10-08 10:52 UTC
Labels: help wanted, question
