### ISSUE TITLE
[ FF7 ] Save files keep getting deleted (Steam version)

### ISSUE THREAD

**Issue by ArhumMK** [julianxhokaxhiu/FFNx#459] opened 2022-06-28 18:59 UTC
I'm using FFNx-v1.12.0.0 on a fresh Steam Install of the game, No mods installed.

This has happened to me twice now. Starting the game up after a while it shows there are no saves available and upon checking the save directory, save00.ff7 is missing. It happened once when I had cloud saving enabled in the launcher, so I disabled it and started a new playthrough and it happened again, lost about 6 hours of playtime. (The game also only allows me to save in in "Save 1" slot, it says "Invalid save file!" if i try to save in the other slots, if that has any relation to this)

It's strange as I haven't found a way to reproduce it on command but saves don't immediately get deleted, As I've saved multiple times and closed and reopened the game several times to test if it happens again. It has only happened when starting the game after some time has passed in between. 

This could be happening randomly, or maybe some part of the Savefile preservation feature failed? I just don't know how this is happening (My Internet is stable and was always online, this bug has occurred with Cloud saving on and off). I've attached the log, but not sure if this is helpful.

Thank you.
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/9004012/FFNx.log)

Update: Under the FF7 Enhancements "MODDER OPTIONS" section I changed the save_path from "save" to "" as the comment says it does not work with the Steam version. Now I am able to access Save 2, 3 and other blocks. Maybe this is causing it?

Update 2: Nope it happened again, completely random?? Booted the game and Save 1's saves disappeared, but the one I saved on Save 2 is available. I give up: [FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/9004341/FFNx.log)

**Comment by julianxhokaxhiu** [comment] 2022-06-30 18:20
I've pushed a tentative patch which I think should solve this issue. Please consider trying any canary >= 1.12.0.40

**Comment by ArhumMK** [comment] 2022-07-01 09:06
Regret to inform you it happened again, with the latest canary build. I didn't have the save folder opened at that moment so I don't know if the saves got deleted on launch or after closing the previous session. 
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/9027613/FFNx.log)

**Comment by julianxhokaxhiu** [comment] 2022-07-03 10:16
I did some personal test on this scenario and I am not able to replicate the issue. As long as you install the Steam release of FFNx, you should be fine. I did 5 launches ( cold ones, closing even the launcher ), did some saves in different spots, closed the game, closed the launcher and repeating the overall process. No save files were lost and the metadata files in the steam user profile folder was updated correctly.

The only suggestion I can give to you is ensure you've disabled the cloud saves feature in the FF7 launcher.

Cheers!

**Closed by julianxhokaxhiu** 2022-07-03 10:16 UTC
Labels: bug

**Comment by ArhumMK** [comment] 2022-07-03 10:26
Welp, I have tried fresh installs again and I'm out of Ideas, Cloud saving is indeed turned off in the launcher but I am logged into my Square account, does that have any effect? In the FFVII save folder in Documents, "cloud_feature_setted" file appears regardless of cloud turned on or off. and the files in the cache folder is also regularly modified, do these have any effect on this issue? Thanks again for testing this issue, seems like it might be something on my end I haven't managed to figure out.

**Comment by julianxhokaxhiu** [comment] 2022-07-03 10:58
I'm not sure where that files comes from but looks like you have the cloud saving feature enabled. FYI this is how it should look like in the launcher:
![image](https://user-images.githubusercontent.com/1237070/177036489-7d95fc4e-2331-4c1b-8a30-19d7b17ac777.png)

**Comment by ArhumMK** [comment] 2022-07-03 11:03
It was disabled like that in the launcher yes. 
I've reinstalled the game again and this time let the vanilla game load, sync saves and then disable cloud saving again, followed by installing FFNx (canary) again. This time it isn't deleting saves on launch for now, hopefully this fixed it.

**Comment by julianxhokaxhiu** [comment] 2022-07-03 11:05
I thought you did that step already, as it is stated in the installation instructions: https://github.com/julianxhokaxhiu/FFNx/blob/master/docs/how_to_install.md#2013-steam-release

Glad you managed to find your way out.

**Comment by ArhumMK** [comment] 2022-07-11 16:51
Sorry if this annoys you, but just putting this here that the same issue is still present, I have tried absolutely everything, Completely clean installs step-by-step etc. All I've gathered is that it happens as soon as the launcher is opened, Offline, or Online, With Cloud Saving disabled before and after installation of FFNx. Unsure if FFNx is causing this alone or in conjunction with the launcher's 'forced' save-deleting behavior even if cloud saving is disabled. It is very strange that this is repeatedly (and randomly) happening for me. 

Apparently this can happen when there is a metadata mismatch, but I don't touch my save folder at all unless deleted so I don't see how the metadata magically doesn't match sometimes.

**Comment by julianxhokaxhiu** [comment] 2022-07-11 17:40
Check when that happens if this log message is present on the `FFNx.log`: https://github.com/julianxhokaxhiu/FFNx/blob/master/src/metadata.cpp#L184

**Comment by ArhumMK** [comment] 2022-07-11 19:22
Yup this line is present every time I've checked the log now and then. Here's me saving multiple times at the same save point, then exiting the game; Save was deleted next time I launched: [FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/9086971/FFNx.log)

**Comment by julianxhokaxhiu** [comment] 2022-07-11 19:55
Did you follow the installation steps making sure you run at least the game once as it comes from Steam with the Cloud option disabled? Tbh I don't know what to think about. If FFNx does its job on the metadata patching, either your file is not updated ( which means permission problems and/or OS problems on your own side ) or you have multiple steam profiles so FFNx is not always using the right path.

Either way is a configuration/behavior problem on your own side. I'm sorry, I am not able to reproduce this issue nor the log does something wrong. Everything works as expected, on the code side.

**Comment by ArhumMK** [comment] 2022-07-11 20:04
I have followed the steps each time yes. 

I Understand this is an issue on my end. I'm just puzzled as to why this is still happening after trying every possible tweak, even more so the fact that sometimes the save files Don't get deleted and work fine. Truly random. Thanks for the continued support. I'll stick to vanilla for now and try this again in the future and hopefully some Windows update or hell, magic itself fixes this later on lmao.

**Comment by julianxhokaxhiu** [comment] 2022-07-11 20:13
If you use 7th Heaven you get all the benefits of Steam without the Steam launcher issues. If I were you I'd give that a spin.

**Comment by ArhumMK** [comment] 2022-07-11 21:23
Thanks will do, didn't know it had steam support until now. 

Also, If I were to delete the launcher and then rename "ff7_en.exe" to "FF7_Launcher.exe" , would that cause any issues with the steam achievements feature? If not, this skips opening the launcher and boots straight into the game, fixing the save deletion issue, similarly how 7th heaven loads the game without launcher.

**Comment by julianxhokaxhiu** [comment] 2022-07-11 21:51
No idea, that's the original FF7 Steam code which was never touched nor reverse engineered AFAIK.

With 7th you can safely use FFNx and have Steam Achievements as well, so it's a win-win on your side.
