### ISSUE TITLE
[ FF7 ] Spotted some missing background in widescreen Mt Nibel

### ISSUE THREAD

**Issue by Taser9001** [julianxhokaxhiu/FFNx#620] opened 2023-11-04 19:27 UTC
Spotted some missing background in the bottom left of the bridge scene in Mt Nibel. 

![image](https://github.com/julianxhokaxhiu/FFNx/assets/149901842/fa3f3d24-91ac-436b-a0ce-e70a6ef4d6dc)

This was during someone else's stream, so I cannot provide GPU info.

**Comment by julianxhokaxhiu** [comment] 2023-11-04 19:52
Duplicate of #474

**Closed by julianxhokaxhiu** 2023-11-04 19:52 UTC
Labels: bug
